language: ruby
branches:
  only:
    - master
cache:
  bundler: true
  pip: true
  yarn: true
  directories:
    - _assets/yarn
rvm: 2.4.3
node_js: "8"
python: 3.4
install:
  - ./bin/setup
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y aspell aspell-en
  - pip install --user proselint
  - npm install -g markdown-spellcheck
script:
  - bundle exec jekyll build --trace
  - bundle exec htmlproofer ./_site --only-4xx --allow-hash-href --assume-extension --check-opengraph --url-ignore "feed.xml"
  - bundle exec danger
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && "./bin/automated"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES: true
  - GITHUB_USERNAME: Milan Vit
  - GITHUB_EMAIL: milanvit@milanvit.net
  - CLOUDFRONT_ZONE_ID: 9f7f8ee361f355357f2463e64a170d0f
  - CLOUDFRONT_AUTH_EMAIL: milanvit@milanvit.net
  - secure: nrpfexcWiW1VhDpJlFCwXu1BjiLC/YfNdGkFBqW50n88Zz3Kt0ydaHYqy1TiJSkC0uxo7zVV4CHRaVjQhuEjpcPAft+X5JCgKaTBq2aG0Xc1BOYk3b/mJwVtv0NM5mkp1k+/kAINjcAO2s+X/pyaaakxaArEyZQmz+KuQuih/wJCJlP0EZLpXSaf/9CfOgidwJOd56m41/KuJTZ6mSazSnjI9uno02HnYxhwFjO1sSTkMxawRLrOHtJIEZEqoPkzzxlIx+19kcimkdthMAIrMse4fBA2gC7f9+PnTJvWf7NlyOfCc/mID6HI2wTL/StAkbaNp6WywK8w6++c7l5mz+V8qkLy5v29MGvPQ5gdilWyyrTsqVD1tUTjK109ShNrjtgWNvbJe5WPhYG8SCphlxBDOr7uHYwtcjaUaiLZSvTH1fAK77RMPd3vodJMB0hNIyIJ0uTtKU5UXYZyNaq1xzfREWhEDEA2qpThNwJoMrnwHo/ZIc7TJsnqPcgesuBwBUlaJ9jGcQBQrtkmGPPUd1ACVLtMg48uHGY3OuxfDnbm4OyxsJFx3KajYUDQ6gv+YoQnWBdovsFKJFSOMICrhGMuGIz7MsgBFtPNzLVUVJ+RObzMn7MZthJMI2gXEe+QcjSSd0oNdzTFF1fTvYFU+I+C+zR4ptd48Ln+zNTCgx0=
  - secure: nVRzBOTs2LxlRHCdOsS3jpuQYqx9ZZ9XwaqwaVdx7T2Qq6WF1aOJ6aCCzuCbGwQgA8U8uNfSloIVe0YDCQtho0m3X7lejuQybvxncdFMdwvovQ/fx1h63gXqUksU5NtxIKtdTc35n1lYrxK2VlR7cdrIDdfD1c0Uu1rE2z+5ooTgkEz0XEzukFuG1MHZjUxyvO/PGGN5bksH+/00meDT8GdrthyrulrOb1EBMFPFZ1KCrPVV10YBgF5RPSkf1f29Cw4OGljjgb+sk9XvHF3oSVrBrDvjJ4GpAzzoBlupn0xVwESosjk9kp/2BrkG688EyIacqgvSyyv2vL6I1kLggLhPMI46WpbdsWbweL9mSF22m1jwmwhDp9WM9mQ4FKWJ/YEE3T7cGgy3Xt84TyhB9i2s9H3XXpz/7KwShNybS5jD4+hgUfCQ/s/7PDl04BF0iDjDPtn6hJeCCOiJvCnOIOszFjb0LsiFSJVZZDoFtgy4HCTRLwJgRAgPsysc6QSarIAA4DN4QX+eRUyfvYcXUfOE1673MSkF/dyfyXrNiFT+F6elDVp1Uohs8yTCLlM10OsfZcI0/wzjrbpPducWjUrjekwn9FB6aknsoSPlvJywfpxvA4XaqBFp5Gi/fNxc7lvX49L20EwtqTOXmkbumlCL2izpR9WDrFt9Wf+KYJQ=
notifications:
  email: false
